// Ye-Almaz — Payroll Routes
// netPay = baseSalarySnapshot + sum(adjustments), rounded to 2dp at every
// write (stricter than Payment.amount elsewhere in this codebase — this is
// the most financially sensitive part of the app, so it gets the extra
// rigor). No automatic tax/pension deduction is ever computed.
//
// Phase 2: run-creation now auto-generates PayrollAdjustment rows from
// whatever's already in the system for that period — the employee's
// active Salary Structure (allowances/deductions), APPROVED overtime,
// ACTIVE advance/loan installments, and FINANCE_APPROVED expense claims —
// rather than leaving every one of those as a separate manual step. HR can
// still add/see manual adjustments on top; auto-generated ones are flagged
// (autoGenerated: true) so the two are never confused in the UI.
const express = require('express');
const { PrismaClient } = require('@prisma/client');
const { protect, restrict } = require('../middleware/auth');
const { appCache, invalidate } = require('../cache');
const { resolveActiveSalaryStructure, computeStructureLines } = require('../services/salaryStructure');

const router = express.Router();
const prisma = new PrismaClient();

const round2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;

// Sequential workflow — advancing only ever moves one step forward.
// FINALIZED is the terminal "Closed" state (kept as FINALIZED rather than
// renamed, to avoid an enum-value migration for the Phase 1 rows already
// using it).
const WORKFLOW = ['DRAFT', 'PROCESSING', 'REVIEW', 'APPROVED', 'PAID', 'FINALIZED'];
// Manual adjustments are only allowed before a run is APPROVED — once
// approved, changing numbers needs a new correction, not a silent edit.
const ADJUSTABLE_STATUSES = ['DRAFT', 'PROCESSING', 'REVIEW'];

async function buildAutoAdjustments(tx, emp, periodMonth, periodYear, from, to) {
  const lines = []; // { label, amount, type, autoGenerated: true }
  const baseSalary = emp.employeeProfile?.baseSalary || 0;

  // 1 + 2. Salary structure (allowances/deductions) and overtime — priced
  // via a PER_OVERTIME_HOUR structure component if one exists (in which
  // case the underlying OvertimeRecord rows are marked PAID so they're
  // never picked up twice), otherwise surfaced as an informational
  // 0-amount line so unpriced overtime is visible rather than silently
  // dropped.
  const structure = await resolveActiveSalaryStructure(tx, emp.id, to);
  const approvedOt = await tx.overtimeRecord.findMany({ where: { userId: emp.id, date: { gte: from, lte: to }, approvalStatus: 'APPROVED', payrollStatus: 'UNPAID' } });
  const totalOtHours = approvedOt.reduce((s, r) => s + r.overtimeHours, 0);
  const hasOvertimeComponent = structure?.items?.some(i => i.component.calcType === 'PER_OVERTIME_HOUR');

  if (structure) {
    // unitsProduced has no reliable per-employee source in this system yet
    // (case units aren't individually attributed) — PER_UNIT components
    // resolve to 0 rather than a fabricated number.
    const structureLines = computeStructureLines({ structure, baseSalary, approvedOvertimeHours: totalOtHours, unitsProduced: 0 });
    for (const l of structureLines) {
      if (l.amount === 0) continue;
      lines.push({ label: l.label, amount: l.amount, type: l.category === 'DEDUCTION' ? 'DEDUCTION' : 'ALLOWANCE' });
    }
  }
  if (hasOvertimeComponent && totalOtHours > 0) {
    lines.push({ label: '', amount: 0, type: 'OVERTIME', _markOvertimePaidIds: approvedOt.map(r => r.id), _silent: true });
  } else if (totalOtHours > 0) {
    lines.push({ label: `Overtime (${totalOtHours}h, no rate configured — 0 Br)`, amount: 0, type: 'OVERTIME' });
  }

  // 3. Active advance/loan installment
  const advances = await tx.employeeAdvance.findMany({ where: { userId: emp.id, status: 'ACTIVE', outstandingBalance: { gt: 0 } } });
  for (const adv of advances) {
    const due = round2(Math.min(adv.installmentAmount, adv.outstandingBalance));
    if (due > 0) lines.push({ label: `${adv.type === 'LOAN' ? 'Loan' : 'Advance'} repayment`, amount: -due, type: 'ADVANCE_REPAYMENT', _advanceId: adv.id, _advanceDue: due });
  }

  // 4. Finance-approved, not-yet-reimbursed expense claims
  const claims = await tx.expenseClaim.findMany({ where: { userId: emp.id, status: 'FINANCE_APPROVED' } });
  for (const c of claims) {
    lines.push({ label: `Expense reimbursement — ${c.category}`, amount: round2(c.amount), type: 'REIMBURSEMENT', _expenseClaimId: c.id });
  }

  // 5. Approved incentive awards for this exact period, not yet paid
  const awards = await tx.incentiveAward.findMany({ where: { userId: emp.id, periodMonth, periodYear, status: 'APPROVED' }, include: { rule: true } });
  for (const a of awards) {
    if (a.awardedAmount > 0) lines.push({ label: `Incentive — ${a.rule.name}`, amount: round2(a.awardedAmount), type: 'INCENTIVE', _incentiveAwardId: a.id });
  }

  return lines;
}

// ── POST /api/payroll/runs ─────────────────────────────────
router.post('/runs', protect, restrict('HR_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const { periodMonth, periodYear } = req.body || {};
    const month = parseInt(periodMonth), year = parseInt(periodYear);
    if (!month || month < 1 || month > 12 || !year) {
      return res.status(400).json({ error: 'A valid periodMonth (1-12) and periodYear are required.' });
    }

    const existing = await prisma.payrollRun.findUnique({ where: { periodMonth_periodYear: { periodMonth: month, periodYear: year } } });
    if (existing) return res.status(409).json({ error: `A payroll run already exists for ${month}/${year}.` });

    const from = new Date(year, month - 1, 1);
    const to = new Date(year, month, 0, 23, 59, 59, 999);

    const employees = await prisma.user.findMany({
      where: { isActive: true, employeeProfile: { employmentStatus: 'ACTIVE' } },
      include: { employeeProfile: true },
    });

    let missingSalaryCount = 0;
    const run = await prisma.$transaction(async (tx) => {
      const created = await tx.payrollRun.create({
        data: { periodMonth: month, periodYear: year, createdById: req.user.id },
      });

      for (const emp of employees) {
        const salary = emp.employeeProfile.baseSalary;
        if (salary == null) missingSalaryCount++;
        const baseSalarySnapshot = round2(salary || 0);

        const autoLines = await buildAutoAdjustments(tx, emp, month, year, from, to);
        const netPay = round2(baseSalarySnapshot + autoLines.reduce((s, l) => s + l.amount, 0));

        const entry = await tx.payrollEntry.create({
          data: { runId: created.id, userId: emp.id, baseSalarySnapshot, netPay },
        });

        for (const line of autoLines) {
          if (!line._silent) {
            await tx.payrollAdjustment.create({
              data: { entryId: entry.id, label: line.label, amount: line.amount, type: line.type, autoGenerated: true, addedById: req.user.id },
            });
          }
          if (line._markOvertimePaidIds?.length) {
            await tx.overtimeRecord.updateMany({ where: { id: { in: line._markOvertimePaidIds } }, data: { payrollStatus: 'PAID' } });
          }
          if (line._advanceId) {
            const remaining = round2((await tx.employeeAdvance.findUnique({ where: { id: line._advanceId } })).outstandingBalance - line._advanceDue);
            await tx.employeeAdvance.update({ where: { id: line._advanceId }, data: { outstandingBalance: Math.max(0, remaining), status: remaining <= 0 ? 'COMPLETED' : 'ACTIVE' } });
            await tx.advanceRepayment.create({ data: { advanceId: line._advanceId, payrollEntryId: entry.id, amount: line._advanceDue } });
          }
          if (line._expenseClaimId) {
            await tx.expenseClaim.update({ where: { id: line._expenseClaimId }, data: { status: 'REIMBURSED', reimbursedInPayrollEntryId: entry.id } });
          }
          if (line._incentiveAwardId) {
            await tx.incentiveAward.update({ where: { id: line._incentiveAwardId }, data: { status: 'PAID', payrollEntryId: entry.id } });
          }
        }
      }
      return created;
    });

    await invalidate('payroll:runs*', 'dashboard:hr-summary', 'advances:*', 'expenses:*', 'incentives:*');
    res.status(201).json({ run, employeeCount: employees.length, missingSalaryCount });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Could not create payroll run.' });
  }
});

// ── GET /api/payroll/runs ──────────────────────────────────
router.get('/runs', protect, restrict('HR_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const runs = await prisma.payrollRun.findMany({
      include: { createdBy: { select: { name: true } }, _count: { select: { entries: true } } },
      orderBy: [{ periodYear: 'desc' }, { periodMonth: 'desc' }],
    });
    res.json(runs);
  } catch (err) {
    res.status(500).json({ error: 'Could not load payroll runs.' });
  }
});

// ── GET /api/payroll/runs/:id ───────────────────────────────
router.get('/runs/:id', protect, restrict('HR_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const run = await prisma.payrollRun.findUnique({
      where: { id: req.params.id },
      include: {
        createdBy: { select: { name: true } },
        entries: {
          include: { user: { select: { id: true, name: true, email: true } }, adjustments: { orderBy: { createdAt: 'asc' } } },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    if (!run) return res.status(404).json({ error: 'Payroll run not found.' });
    // Employer-cost summary for the run detail view — gross earnings vs
    // deductions vs net, across all entries.
    let grossEarnings = 0, deductions = 0;
    for (const e of run.entries) {
      grossEarnings += e.baseSalarySnapshot + e.adjustments.filter(a => a.amount > 0).reduce((s, a) => s + a.amount, 0);
      deductions += e.adjustments.filter(a => a.amount < 0).reduce((s, a) => s + a.amount, 0);
    }
    const totalNetPay = round2(run.entries.reduce((s, e) => s + e.netPay, 0));
    res.json({ ...run, totals: { grossEarnings: round2(grossEarnings), deductions: round2(deductions), netPay: totalNetPay } });
  } catch (err) {
    res.status(500).json({ error: 'Could not load payroll run.' });
  }
});

// ── POST /api/payroll/entries/:id/adjustments ───────────────
router.post('/entries/:id/adjustments', protect, restrict('HR_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const { label, amount, type } = req.body || {};
    if (!label || !label.trim() || amount == null || isNaN(parseFloat(amount))) {
      return res.status(400).json({ error: 'label and amount are required.' });
    }
    const entry = await prisma.payrollEntry.findUnique({ where: { id: req.params.id }, include: { run: true, adjustments: true } });
    if (!entry) return res.status(404).json({ error: 'Payroll entry not found.' });
    if (!ADJUSTABLE_STATUSES.includes(entry.run.status)) return res.status(400).json({ error: `This payroll run is ${entry.run.status} — no further adjustments can be added.` });

    const signedAmount = round2(parseFloat(amount));
    const [, updated] = await prisma.$transaction([
      prisma.payrollAdjustment.create({
        data: { entryId: entry.id, label: label.trim(), amount: signedAmount, type: type || 'OTHER', addedById: req.user.id },
      }),
      prisma.payrollEntry.update({
        where: { id: entry.id },
        data: { netPay: round2(entry.baseSalarySnapshot + entry.adjustments.reduce((s, a) => s + a.amount, 0) + signedAmount) },
        include: { adjustments: true },
      }),
    ]);

    await invalidate('payroll:runs*', 'payroll:entries*');
    res.status(201).json(updated);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Could not add adjustment.' });
  }
});

// ── PATCH /api/payroll/runs/:id/advance ─────────────────────
// Moves the run exactly one step forward in DRAFT→PROCESSING→REVIEW→
// APPROVED→PAID→FINALIZED. Never skips or goes backward.
router.patch('/runs/:id/advance', protect, restrict('HR_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const run = await prisma.payrollRun.findUnique({ where: { id: req.params.id } });
    if (!run) return res.status(404).json({ error: 'Payroll run not found.' });
    const idx = WORKFLOW.indexOf(run.status);
    if (idx === -1 || idx === WORKFLOW.length - 1) return res.status(400).json({ error: `This run is already ${run.status}.` });
    const next = WORKFLOW[idx + 1];

    const updated = await prisma.payrollRun.update({
      where: { id: run.id },
      data: { status: next, ...(next === 'FINALIZED' ? { finalizedAt: new Date() } : {}) },
    });
    await invalidate('payroll:runs*', 'payroll:entries*', 'dashboard:hr-summary');
    res.json(updated);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Could not advance payroll run.' });
  }
});

// ── PATCH /api/payroll/runs/:id/finalize ────────────────────
// Kept for backward compatibility (Phase 1 callers) — jumps straight to
// FINALIZED regardless of current step, same as before.
router.patch('/runs/:id/finalize', protect, restrict('HR_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const run = await prisma.payrollRun.findUnique({ where: { id: req.params.id } });
    if (!run) return res.status(404).json({ error: 'Payroll run not found.' });
    if (run.status === 'FINALIZED') return res.status(400).json({ error: 'This run is already finalized.' });

    const updated = await prisma.payrollRun.update({
      where: { id: run.id },
      data: { status: 'FINALIZED', finalizedAt: new Date() },
    });
    await invalidate('payroll:runs*', 'payroll:entries*', 'dashboard:hr-summary');
    res.json(updated);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Could not finalize payroll run.' });
  }
});

// ── GET /api/payroll/summary ────────────────────────────────
// Shared by AdminHR.jsx's own KPIs and AdminDashboard.jsx's HR section,
// same "one endpoint feeds both" trick as dashboard:inventory-summary.
router.get('/summary', protect, restrict('HR_MANAGER', 'ADMIN'), async (req, res) => {
  const cacheKey = 'dashboard:hr-summary';
  const cached = await appCache.get(cacheKey);
  if (cached) return res.json(cached);
  try {
    const [missingProfileCount, currentRun] = await Promise.all([
      prisma.user.count({ where: { isActive: true, isSharedAccount: false, OR: [{ employeeProfile: null }, { employeeProfile: { baseSalary: null } }] } }),
      prisma.payrollRun.findFirst({ orderBy: [{ periodYear: 'desc' }, { periodMonth: 'desc' }] }),
    ]);
    const result = {
      missingProfileCount,
      currentRunStatus: currentRun?.status || null,
      currentRunPeriod: currentRun ? `${currentRun.periodMonth}/${currentRun.periodYear}` : null,
    };
    await appCache.set(cacheKey, result);
    res.json(result);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Could not load payroll summary.' });
  }
});

module.exports = router;
